version: 2

shared_ghpages: &shared_ghpages
  working_directory: ~/repo
  environment:
    TERM: dump

  steps:
    - checkout
    - run:
        name: install dependencies
        command: |
          bundle install --jobs=4 --retry=3 --path vendor/bundle

    - add-ssh-keys:
        fingerprints:
          - "af:38:77:24:f4:c6:33:f2:74:60:e5:cc:76:0e:a7:ad"

    - run:
        name: publish gh-pages
        command: |
          git config --global user.email "ghpages@dmexe.me"
          git config --global user.name $CIRCLE_USERNAME
          bin/ghpages

shared_ruby_build: &shared_ruby_build
  working_directory: ~/repo
  environment:
    TERM: dump

  steps:
    - checkout
    # Download and cache dependencies
    - run:
        name: install dependencies
        command: |
          bundle install --jobs=4 --retry=3 --path vendor/bundle

    - run:
        name: compile
        command: |
          bin/rake compile

    - run:
        name: run tests
        command: |
          bin/rake test TESTOPTS="--ci-dir=$CIRCLE_TEST_REPORTS/reports"

    - run:
        name: run bench
        command: |
          bin/rake bench

    - store_test_results:
        path: /reports

    - store_artifacts:
        path: /reports
        destination: test-results

jobs:
  ruby22:
    <<: *shared_ruby_build
    docker:
      - image: ruby:2.2
  ruby24:
    <<: *shared_ruby_build
    docker:
      - image: ruby:2.4
  ruby25:
    <<: *shared_ruby_build
    docker:
      - image: ruby:2.5
  ghpages:
    <<: *shared_ghpages
    docker:
      - image: ruby:2.5

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - ruby22
      - ruby24
      - ruby25
      - ghpages:
          requires:
            - ruby22
            - ruby24
            - ruby25
          filters:
            branches:
              only: master


