name: Ruby

runs-on: self-hosted
on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.2
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.2.x
    - name: Build and test with Rake
      run: |
        gem install bundler -v 1.15
        bundle install --jobs 4 --retry 3
        bundle exec rake
