name: Ruby

on: [push]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Build and test with Rake
      run: |
        gem install bundler -v 1.15
        bundle install --jobs 4 --retry 3
        bundle exec rake
